import { z } from 'zod';
import { ActuationKindSchema, type ActuationKind } from './capability.js';
import { ContextKindSchema, SurfaceSchema, type Surface } from './context.js';

/**
 * Capability registry: non-authorizing metadata for promoting host APIs into the product.
 *
 * The registry is deliberately descriptive. It can teach the skill/UI how to discover and use a
 * capability, but it never makes a write executable. A write is executable only when the active
 * bridge advertises the exact ActuationKind in its live CapabilityManifest.
 */

export const CapabilityPromotionStatusSchema = z.enum([
  'implemented',
  'promotable',
  'catalog-only',
  'estate-gated',
  'blocked-host-api',
]);
export type CapabilityPromotionStatus = z.infer<typeof CapabilityPromotionStatusSchema>;

export const CapabilityExposureSchema = z.enum([
  'core-verb',
  'specialized',
  'context-only',
  'estate',
]);
export type CapabilityExposure = z.infer<typeof CapabilityExposureSchema>;

export const CapabilityPrioritySchema = z.enum(['p0', 'p1', 'p2', 'p3']);
export type CapabilityPriority = z.infer<typeof CapabilityPrioritySchema>;

export const RequirementSetSchema = z.object({
  name: z.string(),
  minVersion: z.string(),
  notes: z.string().optional(),
});
export type RequirementSet = z.infer<typeof RequirementSetSchema>;

export const CapabilityRegistryEntrySchema = z.object({
  kind: ActuationKindSchema,
  surface: SurfaceSchema,
  status: CapabilityPromotionStatusSchema,
  exposure: CapabilityExposureSchema,
  priority: CapabilityPrioritySchema,
  command: z.string(),
  title: z.string(),
  useWhen: z.string(),
  hostApis: z.array(z.string()),
  requirementSets: z.array(RequirementSetSchema),
  contextKinds: z.array(ContextKindSchema),
  discovery: z.array(z.string()),
  sequence: z.array(z.string()),
  examples: z.array(z.string()).default([]),
  preview: z.array(z.string()),
  inverse: z.string(),
  provenance: z.string(),
  failureModes: z.array(z.string()),
  skillRefs: z.array(z.string()).default([]),
});
export type CapabilityRegistryEntry = z.infer<typeof CapabilityRegistryEntrySchema>;

export const CAPABILITY_REGISTRY: readonly CapabilityRegistryEntry[] = [
  entry({
    kind: 'write-cells',
    surface: 'excel',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'set/grid/spill',
    title: 'Excel cell and grid writes',
    useWhen: 'write scalar cells, literal rectangular grids, or composed table results into Excel',
    hostApis: ['Excel.Range.values', 'Excel.Range.formulas'],
    requirementSets: [{ name: 'ExcelApi', minVersion: '1.1' }],
    contextKinds: ['range', 'sheet', 'table'],
    discovery: ['outline', 'read <A1|NamedRange>', 'tables', 'properties <range-ref>'],
    sequence: [
      'Use read/list/properties to identify the exact range.',
      'Use grid for literal rectangular data and spill for composed table output.',
      'Keep one logical grid as one effect so the approval card previews it once.',
    ],
    examples: ['grid Report!A1:B2 = "Region\\tRevenue\\nEast\\t100"'],
    preview: ['affected range', 'full grid dimensions', 'formula cells called out separately'],
    inverse: 'restore prior cell values/formulas for the affected range',
    provenance: 'record changeId, range, dimensions, formula count, and source metadata',
    failureModes: ['stale range', 'formula policy rejection', 'write cap exceeded'],
    skillRefs: ['references/excel-semantics.md', 'patterns/top-n-report.md'],
  }),
  entry({
    kind: 'format-cells',
    surface: 'excel',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'format',
    title: 'Excel cell formatting',
    useWhen: 'apply safe visual formatting to an exact worksheet range',
    hostApis: [
      'Excel.Range.format.font.bold',
      'Excel.Range.format.font.italic',
      'Excel.Range.format.fill.color',
      'Excel.Range.numberFormat',
    ],
    requirementSets: [{ name: 'ExcelApi', minVersion: '1.1' }],
    contextKinds: ['range', 'sheet', 'table'],
    discovery: ['read <range>', 'properties <range-ref>', 'open <range-ref>'],
    sequence: [
      'Read or resolve the target range first.',
      'Preview the exact formatting facets and range.',
      'Emit one format command for the affected range.',
    ],
    examples: ['format Sales!A1:C1 bold=true fill=#FFF2CC'],
    preview: ['affected range', 'format facets', 'number format if present'],
    inverse: 'restore captured prior formatting facets on the same range',
    provenance: 'record range, formatting delta, prior formatting snapshot, and changeId',
    failureModes: ['stale range', 'unsupported format facet', 'protected sheet'],
    skillRefs: ['references/excel-semantics.md'],
  }),
  entry({
    kind: 'create-table',
    surface: 'excel',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'table',
    title: 'Excel native table promotion',
    useWhen: 'promote an exact worksheet range to a native Excel Table',
    hostApis: ['Excel.TableCollection.add', 'Excel.Table.getRange', 'Excel.Table.name'],
    requirementSets: [{ name: 'ExcelApi', minVersion: '1.1' }],
    contextKinds: ['range', 'sheet', 'table'],
    discovery: ['read <range>', 'tables', 'properties <range-ref>'],
    sequence: [
      'Read the candidate range and verify headers.',
      'Preview the exact range and requested table name, if any.',
      'Emit one table command after the range is known.',
    ],
    examples: ['table Report!A1:D20 headers name=ReportTable'],
    preview: ['source range', 'header mode', 'requested name'],
    inverse: 'delete the host-minted table object captured at apply-time',
    provenance: 'record source range hash, host-minted table name, and changeId',
    failureModes: ['range collision', 'invalid table name', 'unsupported requirement set'],
    skillRefs: ['references/excel-semantics.md', 'patterns/top-n-report.md'],
  }),
  entry({
    kind: 'insert-chart',
    surface: 'excel',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'chart',
    title: 'Excel native chart insertion',
    useWhen: 'create an Office-native chart over an exact worksheet range',
    hostApis: ['Excel.ChartCollection.add', 'Excel.Chart.title', 'Excel.Chart.name'],
    requirementSets: [{ name: 'ExcelApi', minVersion: '1.1' }],
    contextKinds: ['range', 'sheet', 'table'],
    discovery: ['read <range>', 'tables', 'properties <range-ref>'],
    sequence: [
      'Read the source range and any adjacent labels/headers needed to understand it.',
      'Classify the visualization goal before choosing a type: trend, ranking, part-to-whole, correlation, or summary of text/schedule data.',
      'For schedules, calendars, sparse ranges, and text-heavy grids, first create a chart-ready summary table, then chart that derived range.',
      'Use bar for ranked categories/long labels, column for short categories, line for ordered dates/times, scatter for numeric X/Y, pie only for <=6 non-negative parts of one total, and area only for cumulative trends.',
      'Preview chart type, series orientation, title, and source range.',
      'Emit one chart command for the final range.',
    ],
    examples: [
      'chart column Report!A1:B11 title="Top regions"',
      'chart bar \'Daily schedule\'!K6:L18 title="Weekly Hours by Activity" series=columns',
    ],
    preview: ['source range', 'chart type', 'series orientation', 'title'],
    inverse: 'delete the host-minted chart object captured at apply-time',
    provenance: 'record source range hash, chart type/title, host-minted chart name, and changeId',
    failureModes: [
      'unsupported chart type',
      'source range too sparse',
      'source range needs a derived summary table',
      'unsupported requirement set',
    ],
    skillRefs: ['references/excel-semantics.md', 'patterns/top-n-report.md'],
  }),
  entry({
    kind: 'format-conditional',
    surface: 'excel',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'cf',
    title: 'Excel conditional formatting',
    useWhen: 'add one safe conditional-format rule to an exact worksheet range',
    hostApis: ['Excel.Range.conditionalFormats.add', 'Excel.ConditionalFormat'],
    requirementSets: [{ name: 'ExcelApi', minVersion: '1.6' }],
    contextKinds: ['range', 'sheet', 'table'],
    discovery: ['read <range>', 'properties <range-ref>', 'tables'],
    sequence: [
      'Read the target range and choose one supported rule.',
      'Screen formula-like rule values for active-content risks.',
      'Emit one cf command for the target range.',
    ],
    examples: ['cf Sales!E2:E200 >100000 fill=#C6EFCE', 'cf Sales!E2:E200 databar'],
    preview: ['affected range', 'rule kind', 'criteria/fill'],
    inverse: 'clear the inserted conditional-format rule by captured ordinal when possible',
    provenance: 'record range, rule details, ordinal, and changeId',
    failureModes: ['unsafe formula', 'unsupported requirement set', 'conditional rule conflict'],
    skillRefs: ['references/excel-semantics.md', 'patterns/anomaly-review.md'],
  }),
  entry({
    kind: 'add-comment',
    surface: 'excel',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'comment',
    title: 'Excel cell comment',
    useWhen: 'attach a comment to the first cell of an exact worksheet range',
    hostApis: ['Excel.CommentCollection.add'],
    requirementSets: [{ name: 'ExcelApi', minVersion: '1.10' }],
    contextKinds: ['range', 'comment'],
    discovery: ['read <range>', 'comments <range>', 'open <range-ref>'],
    sequence: [
      'Resolve the target range or cell first.',
      'Keep the comment text single-purpose and grounded.',
      'Emit one comment command.',
    ],
    examples: ['comment Sales!A16 "anomalous spike; verify source system"'],
    preview: ['target cell/range', 'comment text summary'],
    inverse: 'delete the created comment by captured comment id when available',
    provenance: 'record target cell, comment text hash, sources, and changeId',
    failureModes: ['unsupported requirement set', 'target cell gone', 'empty comment text'],
    skillRefs: ['references/excel-semantics.md', 'patterns/anomaly-review.md'],
  }),
  entry({
    kind: 'comment-reply',
    surface: 'excel',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'reply',
    title: 'Excel comment reply',
    useWhen: 'reply to or resolve an existing Excel comment by id',
    hostApis: ['Excel.CommentReplyCollection.add', 'Excel.Comment.resolved'],
    requirementSets: [{ name: 'ExcelApi', minVersion: '1.10' }],
    contextKinds: ['comment'],
    discovery: ['comments <range>', 'properties <comment-ref>', 'open <comment-ref>'],
    sequence: [
      'List or inspect comments to get the exact id.',
      'Preview reply text and resolve flag.',
      'Emit one reply command.',
    ],
    examples: ['reply {3f2a} "verified against source export"'],
    preview: ['comment id', 'reply text summary', 'resolve flag'],
    inverse: 'remove the created reply if host id is captured; otherwise append-only provenance',
    provenance: 'record comment id, reply text hash, resolve flag, and changeId',
    failureModes: ['comment gone', 'unsupported requirement set', 'empty reply text'],
    skillRefs: ['references/excel-semantics.md'],
  }),
  entry({
    kind: 'insert-pivot',
    surface: 'excel',
    status: 'promotable',
    exposure: 'specialized',
    priority: 'p0',
    command: '/insert-pivot',
    title: 'Excel native PivotTable',
    useWhen:
      'summarize a table/range by row, column, value, or filter fields without hand-building formulas',
    hostApis: ['Excel.Worksheet.pivotTables.add', 'Excel.PivotTable'],
    requirementSets: [{ name: 'ExcelApi', minVersion: '1.8' }],
    contextKinds: ['range', 'table', 'sheet'],
    discovery: ['tables', 'read <source-range>', 'properties <table-ref>'],
    sequence: [
      'Read the source headers and sample rows.',
      'Choose row/value fields from exact headers.',
      'Emit one /insert-pivot with sourceRange, destinationRange, and field lists.',
    ],
    examples: [
      '/insert-pivot sourceRange=Sales!A1:G500 destinationRange=Pivot!A3 rowFields="Region" valueFields="Revenue"',
    ],
    preview: ['source range', 'destination range', 'row/column/value/filter fields'],
    inverse: 'delete the created PivotTable object and restore overwritten destination cells',
    provenance: 'record source range hash, destination, pivot name, field mapping, and changeId',
    failureModes: ['missing header', 'unsupported requirement set', 'destination collision'],
    skillRefs: ['references/excel-semantics.md', 'patterns/top-n-report.md'],
  }),
  entry({
    kind: 'sort-range',
    surface: 'excel',
    status: 'promotable',
    exposure: 'specialized',
    priority: 'p1',
    command: '/sort-range',
    title: 'Excel native sort',
    useWhen: 'sort a range or table in place using Excel sort semantics',
    hostApis: ['Excel.Range.sort.apply', 'Excel.Table.sort.apply'],
    requirementSets: [{ name: 'ExcelApi', minVersion: '1.2' }],
    contextKinds: ['range', 'table'],
    discovery: ['tables', 'read <range>', 'properties <table-ref>'],
    sequence: [
      'Read headers and verify the sort key exists.',
      'Preview the sort key, direction, and affected rows.',
      'Emit one /sort-range command.',
    ],
    examples: ['/sort-range range=Sales!A1:G500 key=Revenue order=descending'],
    preview: ['affected range/table', 'sort key', 'direction', 'header handling'],
    inverse: 'restore prior row order from captured values when within write budget',
    provenance: 'record source hash, sort key, order, and changeId',
    failureModes: ['unknown key', 'large inverse unavailable', 'protected sheet'],
    skillRefs: ['references/excel-semantics.md'],
  }),
  entry({
    kind: 'filter-range',
    surface: 'excel',
    status: 'promotable',
    exposure: 'specialized',
    priority: 'p1',
    command: '/filter-range',
    title: 'Excel native filter',
    useWhen: 'apply an AutoFilter/table filter without deleting or rewriting rows',
    hostApis: ['Excel.AutoFilter.apply', 'Excel.TableColumn.filter.apply'],
    requirementSets: [{ name: 'ExcelApi', minVersion: '1.2' }],
    contextKinds: ['range', 'table'],
    discovery: ['tables', 'read <range>', 'properties <table-ref>'],
    sequence: [
      'Read headers and identify the exact filter column.',
      'Preview criteria and affected table/range.',
      'Emit one /filter-range command.',
    ],
    examples: ['/filter-range range=Sales!A1:G500 column=Region criterion1=East'],
    preview: ['affected range/table', 'column', 'criteria'],
    inverse: 'clear or restore previous filter state when host exposes it',
    provenance: 'record filter criteria, column, source range hash, and changeId',
    failureModes: ['unknown column', 'existing filter conflict', 'unsupported host'],
    skillRefs: ['references/excel-semantics.md'],
  }),
  entry({
    kind: 'manage-worksheet',
    surface: 'excel',
    status: 'catalog-only',
    exposure: 'specialized',
    priority: 'p2',
    command: '/manage-worksheet',
    title: 'Excel worksheet lifecycle',
    useWhen: 'create, rename, activate, protect, unprotect, or delete worksheets',
    hostApis: ['Excel.WorksheetCollection.add', 'Excel.Worksheet.name', 'Excel.Worksheet.activate'],
    requirementSets: [{ name: 'ExcelApi', minVersion: '1.1' }],
    contextKinds: ['sheet'],
    discovery: ['outline', 'list sheet', 'properties <sheet-ref>'],
    sequence: [
      'List sheets and confirm the target name.',
      'For delete/rename/protect, preview the exact worksheet and risk.',
      'Emit one /manage-worksheet command only after the user intent is explicit.',
    ],
    examples: ['/manage-worksheet action=create name=Analysis'],
    preview: ['action', 'worksheet name', 'collision/delete/protection warning'],
    inverse: 'create/rename can be reversed; delete requires snapshot and is often irreversible',
    provenance: 'record worksheet id/name before and after, action, and changeId',
    failureModes: ['name collision', 'protected workbook', 'irreversible delete policy'],
    skillRefs: ['references/excel-semantics.md'],
  }),
  entry({
    kind: 'format-chart',
    surface: 'excel',
    status: 'promotable',
    exposure: 'specialized',
    priority: 'p2',
    command: '/format-chart',
    title: 'Excel chart formatting',
    useWhen: 'retitle or restyle an existing chart without recreating its data source',
    hostApis: ['Excel.Chart.title', 'Excel.Chart.legend', 'Excel.Chart.axes'],
    requirementSets: [{ name: 'ExcelApi', minVersion: '1.1' }],
    contextKinds: ['sheet'],
    discovery: ['list', 'properties <chart-ref>', 'open <chart-ref>'],
    sequence: [
      'Discover the chart ref and data source.',
      'Preview only formatting changes, not data changes.',
      'Emit one /format-chart command.',
    ],
    examples: ['/format-chart chartName=Revenue title="Revenue by region" legend=show'],
    preview: ['target chart', 'changed title/legend/axis/style fields'],
    inverse: 'restore captured chart formatting fields',
    provenance: 'record chart id/name, formatting delta, source range hash, and changeId',
    failureModes: ['chart ref not exposed yet', 'unsupported formatting field'],
    skillRefs: ['references/excel-semantics.md'],
  }),
  entry({
    kind: 'insert-text',
    surface: 'word',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/insert-text',
    title: 'Word plain-text insertion',
    useWhen: 'insert grounded plain text at the current selection or after an exact anchor',
    hostApis: ['Word.Range.insertText', 'Word.Selection.insertText'],
    requirementSets: [{ name: 'WordApi', minVersion: '1.1' }],
    contextKinds: ['selection', 'paragraph', 'document'],
    discovery: ['outline', 'search <anchor>', 'inspect <paragraph-ref>', 'open <paragraph-ref>'],
    sequence: [
      'Resolve the insertion point from selection or exact anchor.',
      'Preview the inserted text and position.',
      'Emit one /insert-text command only when insertion, not tracked rewrite, is intended.',
    ],
    examples: ['/insert-text match="Appendix" position=after text="Reviewed by Legal."'],
    preview: ['anchor/selection', 'position', 'inserted text summary'],
    inverse: 'delete the inserted text range when the inserted range is captured',
    provenance: 'record anchor, inserted text hash, position, and changeId',
    failureModes: ['stale anchor', 'ambiguous insertion point', 'protected range'],
    skillRefs: ['references/word-semantics.md'],
  }),
  entry({
    kind: 'replace-selection',
    surface: 'word',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/replace-selection',
    title: 'Word selection replacement',
    useWhen: 'replace the current Word selection after previewing prior and new text',
    hostApis: ['Word.Range.insertText'],
    requirementSets: [{ name: 'WordApi', minVersion: '1.1' }],
    contextKinds: ['selection'],
    discovery: ['read', 'properties <word:selection>', 'inspect <word:selection>'],
    sequence: [
      'Read the active selection before writing.',
      'Preview prior selected text and replacement text.',
      'Emit one /replace-selection command.',
    ],
    examples: ['/replace-selection text="Updated clause text."'],
    preview: ['selected text hash/summary', 'replacement text summary'],
    inverse: 'restore the prior selection text captured before replacement',
    provenance: 'record selection anchor, prior/new text hashes, and changeId',
    failureModes: ['empty selection', 'selection drift', 'protected range'],
    skillRefs: ['references/word-semantics.md'],
  }),
  entry({
    kind: 'insert-ooxml',
    surface: 'word',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/insert-ooxml',
    title: 'Word screened OOXML insertion',
    useWhen: 'insert a screened rich Word fragment where plain text is insufficient',
    hostApis: ['Word.Range.insertOoxml'],
    requirementSets: [{ name: 'WordApi', minVersion: '1.1' }],
    contextKinds: ['selection', 'paragraph', 'document'],
    discovery: ['outline', 'search <anchor>', 'inspect <paragraph-ref>'],
    sequence: [
      'Resolve the insertion point from exact host content.',
      'Use only sanitized OOXML produced by trusted code paths.',
      'Emit one /insert-ooxml command with the screened fragment.',
    ],
    examples: ['/insert-ooxml match="Appendix" ooxml="<w:p>...</w:p>"'],
    preview: ['anchor', 'OOXML size/hash', 'position'],
    inverse: 'delete the inserted OOXML range when the inserted range is captured',
    provenance: 'record anchor, OOXML hash, sanitizer result, and changeId',
    failureModes: ['malformed OOXML', 'sanitization rejection', 'stale anchor'],
    skillRefs: ['references/word-semantics.md'],
  }),
  entry({
    kind: 'tracked-change',
    surface: 'word',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'suggest',
    title: 'Word tracked rewrite',
    useWhen: 'replace exact existing text as a reviewable tracked change',
    hostApis: ['Word.Range.insertText', 'Word.ChangeTrackingMode'],
    requirementSets: [{ name: 'WordApi', minVersion: '1.1' }],
    contextKinds: ['selection', 'paragraph', 'document'],
    discovery: ['search <exact text>', 'inspect <paragraph-ref>', 'open <paragraph-ref>'],
    sequence: [
      'Read the exact source text before proposing the rewrite.',
      'Anchor on exact text, not a paraphrase.',
      'Emit one suggest command per reviewable rewrite.',
    ],
    examples: ['suggest "99.5%" => "99.9%"'],
    preview: ['old text', 'new text', 'anchor context'],
    inverse: 'reject/remove the tracked change when host revision identity is captured',
    provenance: 'record anchor text hash, replacement hash, sources, and changeId',
    failureModes: ['anchor not found', 'multiple ambiguous matches', 'tracking unavailable'],
    skillRefs: ['references/word-semantics.md', 'patterns/evidence-backed-redline.md'],
  }),
  entry({
    kind: 'fill-content-control',
    surface: 'word',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/fill-content-control',
    title: 'Word content-control fill',
    useWhen: 'populate a known content control by id, tag, or title',
    hostApis: ['Word.ContentControl.insertText', 'Word.ContentControl.tag'],
    requirementSets: [{ name: 'WordApi', minVersion: '1.1' }],
    contextKinds: ['document'],
    discovery: ['list content-control', 'properties <content-control-ref>', 'inspect <ref>'],
    sequence: [
      'Resolve the exact content control first.',
      'Preview prior and new value.',
      'Emit one /fill-content-control command.',
    ],
    examples: ['/fill-content-control contentControlId=42 text="Acme Pty Ltd"'],
    preview: ['content control id/tag/title', 'prior value summary', 'new value summary'],
    inverse: 'restore prior content-control value',
    provenance: 'record contentControlId/tag/title, prior/new value hashes, and changeId',
    failureModes: ['control not found', 'duplicate tag ambiguity', 'locked content control'],
    skillRefs: ['references/word-semantics.md'],
  }),
  entry({
    kind: 'add-comment',
    surface: 'word',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'comment',
    title: 'Word anchored comment',
    useWhen: 'attach a comment to exact selected or matched Word text',
    hostApis: ['Word.CommentCollection.add'],
    requirementSets: [{ name: 'WordApi', minVersion: '1.4' }],
    contextKinds: ['selection', 'paragraph', 'comment'],
    discovery: ['search <anchor>', 'inspect <paragraph-ref>', 'comments <selector>'],
    sequence: [
      'Resolve the exact text range first.',
      'Keep the comment tied to one issue or citation.',
      'Emit one comment command.',
    ],
    examples: ['comment "99.5%" "Policy requires 99.9%; verify SLA."'],
    preview: ['anchor text', 'comment text summary'],
    inverse: 'delete the created comment by captured comment id when available',
    provenance: 'record anchor text hash, comment text hash, sources, and changeId',
    failureModes: ['anchor not found', 'multiple matches', 'comment API unavailable'],
    skillRefs: ['references/word-semantics.md', 'patterns/evidence-backed-redline.md'],
  }),
  entry({
    kind: 'comment-reply',
    surface: 'word',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'reply',
    title: 'Word comment reply',
    useWhen: 'reply to or resolve an existing Word comment by id',
    hostApis: ['Word.CommentReplyCollection.add', 'Word.Comment.resolved'],
    requirementSets: [{ name: 'WordApi', minVersion: '1.4' }],
    contextKinds: ['comment'],
    discovery: ['comments', 'properties <comment-ref>', 'open <comment-ref>'],
    sequence: [
      'List or inspect comments to get the exact id.',
      'Preview reply text and resolve flag.',
      'Emit one reply command.',
    ],
    examples: ['reply {3f2a} "Updated per policy."'],
    preview: ['comment id', 'reply text summary', 'resolve flag'],
    inverse: 'remove created reply when host id is captured; otherwise append-only provenance',
    provenance: 'record comment id, reply text hash, resolve flag, and changeId',
    failureModes: ['comment gone', 'comment API unavailable', 'empty reply text'],
    skillRefs: ['references/word-semantics.md'],
  }),
  entry({
    kind: 'apply-style',
    surface: 'word',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/apply-style',
    title: 'Word paragraph/style application',
    useWhen: 'apply a built-in or known document style to an exact paragraph/range',
    hostApis: ['Word.Paragraph.styleBuiltIn', 'Word.Range.style'],
    requirementSets: [{ name: 'WordApi', minVersion: '1.1' }],
    contextKinds: ['paragraph', 'selection', 'document'],
    discovery: ['list paragraph', 'inspect <paragraph-ref>', 'open <paragraph-ref>'],
    sequence: [
      'Resolve the paragraph/range first.',
      'Preview the style name and exact target.',
      'Emit one /apply-style command.',
    ],
    examples: ['/apply-style match="Executive summary" style="Heading 1"'],
    preview: ['target paragraph/range', 'prior style', 'new style'],
    inverse: 'restore prior style on the same resolved range',
    provenance: 'record range anchor, prior/new style, and changeId',
    failureModes: ['stale anchor', 'unknown style', 'style not supported on host'],
    skillRefs: ['references/word-semantics.md'],
  }),
  entry({
    kind: 'insert-table',
    surface: 'word',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/insert-table',
    title: 'Word native table insertion',
    useWhen: 'insert a small grounded table into a Word document',
    hostApis: ['Word.Range.insertTable', 'Word.Table'],
    requirementSets: [{ name: 'WordApi', minVersion: '1.3' }],
    contextKinds: ['selection', 'paragraph', 'table'],
    discovery: ['search <anchor>', 'inspect <paragraph-ref>', 'open <paragraph-ref>'],
    sequence: [
      'Read the anchor paragraph or current selection.',
      'Keep the table small enough for preview.',
      'Emit one /insert-table with a tableGrid payload or use OOXML when native table is unavailable.',
    ],
    examples: ['/insert-table match="Appendix" rows="Metric\\tValue\\nRevenue\\t100"'],
    preview: ['anchor', 'row/column count', 'first rows'],
    inverse: 'delete the inserted table when a stable inserted range can be re-resolved',
    provenance: 'record anchor, table hash, row/column count, and changeId',
    failureModes: ['stale anchor', 'table too large', 'host lacks native table insert'],
    skillRefs: ['references/word-semantics.md'],
  }),
  entry({
    kind: 'insert-content-control',
    surface: 'word',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/insert-content-control',
    title: 'Word content-control insertion',
    useWhen: 'create a new plain, rich-text, or tagged content control at a resolved Word range',
    hostApis: [
      'Word.Range.insertContentControl',
      'Word.ContentControl.tag',
      'Word.ContentControl.title',
    ],
    requirementSets: [{ name: 'WordApi', minVersion: '1.1' }],
    contextKinds: ['selection', 'paragraph', 'document'],
    discovery: ['search <anchor>', 'inspect <paragraph-ref>', 'properties <word:selection>'],
    sequence: [
      'Resolve the insertion range or active selection.',
      'Choose a content-control type, tag, and title from user intent.',
      'Emit one /insert-content-control command and preview tag/title/type.',
    ],
    examples: [
      '/insert-content-control match="Customer:" type=richText tag=CustomerName title="Customer name"',
    ],
    preview: ['anchor', 'content-control type', 'tag/title', 'initial text if any'],
    inverse: 'delete the created content control by captured id',
    provenance: 'record anchor, contentControlId, tag/title/type, and changeId',
    failureModes: ['stale anchor', 'duplicate tag policy', 'unsupported control type'],
    skillRefs: ['references/word-semantics.md'],
  }),
  entry({
    kind: 'insert-hyperlink',
    surface: 'word',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/insert-hyperlink',
    title: 'Word screened hyperlink',
    useWhen: 'add or update a hyperlink on exact Word text after URL safety screening',
    hostApis: ['Word.Range.hyperlink'],
    requirementSets: [{ name: 'WordApi', minVersion: '1.4' }],
    contextKinds: ['selection', 'paragraph', 'document'],
    discovery: ['search <display text>', 'inspect <paragraph-ref>', 'properties <word:selection>'],
    sequence: [
      'Read the exact display text or selection.',
      'Screen the URL scheme and host before preview.',
      'Emit one /insert-hyperlink command for the resolved range.',
    ],
    examples: [
      '/insert-hyperlink match="release notes" url=https://contoso.example/release displayText="release notes"',
    ],
    preview: ['target range', 'display text', 'screened URL'],
    inverse: 'restore prior hyperlink/display text on the same range',
    provenance: 'record anchor, URL hash, display text hash, and changeId',
    failureModes: ['unsafe URL', 'stale anchor', 'hyperlink API unavailable'],
    skillRefs: ['references/word-semantics.md'],
  }),
  entry({
    kind: 'find-replace',
    surface: 'word',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/find-replace',
    title: 'Word bounded find/replace',
    useWhen: 'replace repeated exact text after previewing hit count and blast radius',
    hostApis: ['Word.Body.search', 'Word.Range.insertText'],
    requirementSets: [{ name: 'WordApi', minVersion: '1.1' }],
    contextKinds: ['document', 'paragraph'],
    discovery: ['search <find text>', 'inspect <hit-ref>', 'properties <hit-ref>'],
    sequence: [
      'Search and preview all hits before writing.',
      'Ask for clarification when the hit count is larger than the policy limit.',
      'Emit one /find-replace command only for explicit bulk replacements.',
    ],
    examples: ['/find-replace find="99.5%" replace="99.9%" matchCase=false'],
    preview: ['hit count', 'sample hits', 'replace text', 'excluded regions'],
    inverse: 'restore prior text for each captured hit when within policy limits',
    provenance: 'record hit anchors, hashes, replace text hash, and changeId',
    failureModes: ['too many hits', 'anchor drift', 'protected/locked range'],
    skillRefs: ['references/word-semantics.md'],
  }),
  entry({
    kind: 'insert-slide',
    surface: 'powerpoint',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'slide',
    title: 'PowerPoint slide insertion',
    useWhen: 'add a grounded title-and-bullets slide to the active deck',
    hostApis: ['PowerPoint.SlideCollection.add', 'PowerPoint.Shape.textFrame'],
    requirementSets: [{ name: 'PowerPointApi', minVersion: '1.2' }],
    contextKinds: ['slide', 'document'],
    discovery: ['slides', 'outline', 'read <slide-ref>', 'properties <deck-ref>'],
    sequence: [
      'Read or inspect the neighboring slide context.',
      'Preview title, bullets, notes-as-chat if notes cannot be written, and insertion point.',
      'Emit one slide command.',
    ],
    examples: ['slide "Q4 risks" "Dependency drift" "Budget pressure"'],
    preview: ['target deck/position', 'title', 'bullet count'],
    inverse: 'delete the inserted slide by captured slide id when available',
    provenance: 'record slide id/index, title/bullets hash, sources, and changeId',
    failureModes: ['unsupported host', 'deck changed before apply', 'speaker notes unavailable'],
    skillRefs: ['references/powerpoint-semantics.md'],
  }),
  entry({
    kind: 'set-shape-text',
    surface: 'powerpoint',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'shape',
    title: 'PowerPoint shape text replacement',
    useWhen: 'replace text in one addressed slide shape without rewriting the whole slide',
    hostApis: ['PowerPoint.Shape.textFrame.textRange.text'],
    requirementSets: [{ name: 'PowerPointApi', minVersion: '1.4' }],
    contextKinds: ['slide', 'shape'],
    discovery: ['slides', 'list shape', 'properties <shape-ref>', 'open <shape-ref>'],
    sequence: [
      'List or inspect shape refs.',
      'Resolve both slide id and shape id.',
      'Emit one shape command with the replacement text.',
    ],
    examples: ['shape pp:shape:s2:shape7 "Updated Q4 outlook"'],
    preview: ['slide id', 'shape id', 'before/after text'],
    inverse: 'restore prior shape text by captured shape id',
    provenance: 'record slide id, shape id, prior/new text hashes, and changeId',
    failureModes: ['stale shape id', 'non-text shape', 'unsupported PowerPointApi'],
    skillRefs: ['references/powerpoint-semantics.md'],
  }),
  entry({
    kind: 'insert-image',
    surface: 'powerpoint',
    status: 'promotable',
    exposure: 'specialized',
    priority: 'p0',
    command: '/insert-image',
    title: 'PowerPoint image insertion',
    useWhen: 'place a generated or grounded image onto a slide as an image object',
    hostApis: ['PowerPoint.ShapeCollection.addImage'],
    requirementSets: [{ name: 'PowerPointApi', minVersion: '1.4' }],
    contextKinds: ['slide', 'shape', 'image'],
    discovery: ['slides', 'open <slide-ref>', 'properties <slide-ref>'],
    sequence: [
      'Resolve the target slide.',
      'Preview image dimensions, alt text, and placement.',
      'Emit one /insert-image command.',
    ],
    examples: ['/insert-image slide=s2 base64=<png> alt="Architecture diagram" left=72 top=96'],
    preview: ['target slide', 'image size', 'alt text', 'placement rectangle'],
    inverse: 'delete the inserted image shape by captured shape id',
    provenance: 'record image hash, slide id, shape id, alt text, and changeId',
    failureModes: ['image too large', 'unsupported host', 'slide no longer exists'],
    skillRefs: ['references/powerpoint-semantics.md'],
  }),
  entry({
    kind: 'format-shape',
    surface: 'powerpoint',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/format-shape',
    title: 'PowerPoint shape formatting',
    useWhen: 'change fill, line, font, or z-order for one addressed shape',
    hostApis: ['PowerPoint.Shape.fill', 'PowerPoint.Shape.lineFormat', 'PowerPoint.TextRange.font'],
    requirementSets: [{ name: 'PowerPointApi', minVersion: '1.4' }],
    contextKinds: ['shape', 'slide'],
    discovery: ['list shape', 'properties <shape-ref>', 'open <shape-ref>'],
    sequence: [
      'Inspect the shape ref first.',
      'Preview the exact formatting delta.',
      'Emit one /format-shape command.',
    ],
    examples: ['/format-shape ref=pp:shape:s2:shape7 fill=#0F6CBD'],
    preview: ['shape id', 'prior formatting fields', 'new formatting fields'],
    inverse: 'restore captured formatting fields on the same shape id',
    provenance: 'record slide id, shape id, formatting delta, and changeId',
    failureModes: ['stale shape id', 'unsupported formatting property'],
    skillRefs: ['references/powerpoint-semantics.md'],
  }),
  entry({
    kind: 'add-shape',
    surface: 'powerpoint',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/add-shape',
    title: 'PowerPoint shape/textbox insertion',
    useWhen:
      'add a text box, geometric shape, or line to an addressed slide with explicit geometry',
    hostApis: [
      'PowerPoint.ShapeCollection.addTextBox',
      'PowerPoint.ShapeCollection.addGeometricShape',
      'PowerPoint.ShapeCollection.addLine',
    ],
    requirementSets: [{ name: 'PowerPointApi', minVersion: '1.4' }],
    contextKinds: ['slide', 'shape'],
    discovery: ['slides', 'open <slide-ref>', 'properties <slide-ref>'],
    sequence: [
      'Resolve the target slide.',
      'Choose explicit left/top/width/height and shape type.',
      'Emit one /add-shape command; never infer placement from prose alone.',
    ],
    examples: [
      '/add-shape slide=s2 shapeType=textBox text="Key risk" left=72 top=96 width=280 height=80',
    ],
    preview: ['target slide', 'shape type', 'geometry', 'text/style fields'],
    inverse: 'delete the inserted shape by captured shape id',
    provenance: 'record slide id, minted shape id, geometry, text hash, and changeId',
    failureModes: ['missing slide', 'invalid geometry', 'unsupported shape type'],
    skillRefs: ['references/powerpoint-semantics.md'],
  }),
  entry({
    kind: 'add-table-slide',
    surface: 'powerpoint',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/add-table-slide',
    title: 'PowerPoint native slide table',
    useWhen: 'insert a small native table onto a slide instead of flattening it into text',
    hostApis: ['PowerPoint.ShapeCollection.addTable'],
    requirementSets: [{ name: 'PowerPointApi', minVersion: '1.8' }],
    contextKinds: ['slide', 'table'],
    discovery: ['slides', 'read <source>', 'context analytical inline-preferred'],
    sequence: [
      'Resolve the target slide and table data.',
      'Keep row/column count small enough for preview.',
      'Emit one /add-table-slide with explicit geometry and TSV rows.',
    ],
    examples: [
      '/add-table-slide slide=s3 rows="Metric\\tValue\\nARR\\t$12M" left=72 top=120 width=560 height=260',
    ],
    preview: ['target slide', 'row/column count', 'geometry', 'first rows'],
    inverse: 'delete the inserted table shape by captured shape id',
    provenance: 'record slide id, table shape id, grid hash, geometry, and changeId',
    failureModes: ['PowerPointApi 1.8 unavailable', 'table too large', 'geometry collision'],
    skillRefs: ['references/powerpoint-semantics.md'],
  }),
  entry({
    kind: 'apply-slide-layout',
    surface: 'powerpoint',
    status: 'catalog-only',
    exposure: 'specialized',
    priority: 'p2',
    command: '/apply-slide-layout',
    title: 'PowerPoint slide layout application',
    useWhen: 'apply an existing deck layout to a specific slide without recreating the slide',
    hostApis: ['PowerPoint.Slide.applyLayout'],
    requirementSets: [{ name: 'PowerPointApi', minVersion: '1.8' }],
    contextKinds: ['slide'],
    discovery: ['slides', 'properties <slide-ref>'],
    sequence: [
      'Resolve the target slide and available layout name/id.',
      'Preview the prior and new layout.',
      'Emit one /apply-slide-layout command.',
    ],
    examples: ['/apply-slide-layout slide=s4 layoutName="Title and Content"'],
    preview: ['target slide', 'prior layout', 'new layout'],
    inverse: 'restore the prior layout id when captured',
    provenance: 'record slide id, prior/new layout id/name, and changeId',
    failureModes: ['PowerPointApi 1.8 unavailable', 'unknown layout', 'stale slide id'],
    skillRefs: ['references/powerpoint-semantics.md'],
  }),
  entry({
    kind: 'reply-mail',
    surface: 'outlook',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'mail',
    title: 'Outlook reviewable reply draft',
    useWhen: 'stage a reply draft for the current message without sending it',
    hostApis: ['Office.MessageRead.displayReplyForm'],
    requirementSets: [{ name: 'Mailbox', minVersion: '1.1' }],
    contextKinds: ['mail-item', 'mail-thread'],
    discovery: ['read', 'attachments', 'properties <mail-ref>'],
    sequence: [
      'Read the current message/thread metadata.',
      'Draft only the body; do not send.',
      'Emit one mail command and let Outlook on-send policy remain the final gate.',
    ],
    examples: ['mail "Thanks — Thursday works for me."'],
    preview: ['draft body summary', 'current message target', 'on-send policy status'],
    inverse: 'draft remains user-reviewable; no sent mail is created',
    provenance: 'record draft target metadata, body hash, and changeId',
    failureModes: ['not a message read surface', 'compose API unavailable', 'on-send policy veto'],
    skillRefs: ['references/outlook-semantics.md'],
  }),
  entry({
    kind: 'create-mail',
    surface: 'outlook',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'compose',
    title: 'Outlook new draft',
    useWhen: 'open a new grounded draft without adding recipients or sending',
    hostApis: ['Office.Mailbox.displayNewMessageForm'],
    requirementSets: [{ name: 'Mailbox', minVersion: '1.6' }],
    contextKinds: ['mail-item', 'person'],
    discovery: ['context inline-preferred', 'properties <source-ref>'],
    sequence: [
      'Ground the subject/body on allowed sources.',
      'Leave recipients for the user unless set-recipients is separately advertised.',
      'Emit one compose command.',
    ],
    examples: ['compose "Follow-up" "Hi — summary below."'],
    preview: ['subject', 'body summary', 'recipient mode'],
    inverse: 'unsent draft remains user-controlled',
    provenance: 'record source metadata, subject/body hashes, and changeId',
    failureModes: ['compose API unavailable', 'policy blocks draft creation'],
    skillRefs: ['references/outlook-semantics.md'],
  }),
  entry({
    kind: 'add-attachment',
    surface: 'outlook',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/add-attachment',
    title: 'Outlook draft attachment',
    useWhen: 'attach a generated or approved file to a draft without sending mail',
    hostApis: [
      'Office.MessageCompose.addFileAttachmentAsync',
      'Office.MessageCompose.addItemAttachmentAsync',
    ],
    requirementSets: [{ name: 'Mailbox', minVersion: '1.8' }],
    contextKinds: ['mail-item', 'attachment', 'file'],
    discovery: ['attachments', 'properties <draft-ref>', 'context upload-preferred'],
    sequence: [
      'Confirm the active item is a draft/compose surface.',
      'Use only a host-returned file or allowlisted URL/base64 artifact.',
      'Emit one /add-attachment command.',
    ],
    examples: ['/add-attachment name="brief.xlsx" base64=<base64>'],
    preview: ['draft target', 'file name', 'size/hash', 'attachment type'],
    inverse: 'remove the created attachment by attachment id when available',
    provenance: 'record attachment name, size/hash, draft id when available, and changeId',
    failureModes: ['not in compose mode', 'file too large', 'unsafe URL'],
    skillRefs: ['references/outlook-semantics.md'],
  }),
  entry({
    kind: 'set-body',
    surface: 'outlook',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/set-body',
    title: 'Outlook draft body update',
    useWhen: 'replace the body of an open draft while leaving send control with the user',
    hostApis: ['Office.Body.setAsync'],
    requirementSets: [{ name: 'Mailbox', minVersion: '1.3' }],
    contextKinds: ['mail-item'],
    discovery: ['read', 'properties <mail-ref>'],
    sequence: [
      'Confirm the item is a compose draft.',
      'Preview the sanitized body delta.',
      'Emit one /set-body command.',
    ],
    examples: ['/set-body html="<p>Thanks, Thursday works.</p>"'],
    preview: ['draft target', 'body mode', 'redacted size/summary'],
    inverse: 'restore prior draft body if captured within size limits',
    provenance: 'record draft target, body hash, coercion type, and changeId',
    failureModes: ['not in compose mode', 'body too large', 'HTML sanitization rejection'],
    skillRefs: ['references/outlook-semantics.md'],
  }),
  entry({
    kind: 'set-recipients',
    surface: 'outlook',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/set-recipients',
    title: 'Outlook draft recipients',
    useWhen: 'set or add recipients on an open draft while preserving final send control',
    hostApis: ['Office.Recipients.setAsync', 'Office.Recipients.addAsync'],
    requirementSets: [{ name: 'Mailbox', minVersion: '1.1' }],
    contextKinds: ['mail-item', 'person'],
    discovery: ['properties <draft-ref>', 'context reference-preferred'],
    sequence: [
      'Confirm compose/draft mode.',
      'Use only user-provided or explicitly grounded recipient addresses.',
      'Emit one /set-recipients with recipientMode=set or add.',
    ],
    examples: ['/set-recipients to="user@contoso.com" cc="reviewer@contoso.com" recipientMode=add'],
    preview: ['draft target', 'to/cc/bcc delta', 'recipient mode'],
    inverse: 'restore captured recipients before the mutation',
    provenance: 'record draft id when available, recipient hashes, mode, and changeId',
    failureModes: ['not in compose mode', 'invalid address', 'policy disallows recipient edits'],
    skillRefs: ['references/outlook-semantics.md'],
  }),
  entry({
    kind: 'set-subject',
    surface: 'outlook',
    status: 'implemented',
    exposure: 'specialized',
    priority: 'p0',
    command: '/set-subject',
    title: 'Outlook draft subject',
    useWhen: 'replace the subject of an open draft without sending',
    hostApis: ['Office.Subject.setAsync'],
    requirementSets: [{ name: 'Mailbox', minVersion: '1.1' }],
    contextKinds: ['mail-item'],
    discovery: ['properties <draft-ref>', 'read'],
    sequence: [
      'Confirm compose/draft mode.',
      'Preview the prior and new subject.',
      'Emit one /set-subject command.',
    ],
    examples: ['/set-subject subject="Updated project plan"'],
    preview: ['draft target', 'prior subject', 'new subject'],
    inverse: 'restore the prior subject',
    provenance: 'record draft id when available, prior/new subject hashes, and changeId',
    failureModes: ['not in compose mode', 'subject API unavailable'],
    skillRefs: ['references/outlook-semantics.md'],
  }),
  entry({
    kind: 'add-categories',
    surface: 'outlook',
    status: 'catalog-only',
    exposure: 'specialized',
    priority: 'p2',
    command: '/add-categories',
    title: 'Outlook category assignment',
    useWhen: 'apply existing mailbox categories to a message or draft',
    hostApis: ['Office.Categories.addAsync', 'Office.Categories.removeAsync'],
    requirementSets: [{ name: 'Mailbox', minVersion: '1.8' }],
    contextKinds: ['mail-item'],
    discovery: ['properties <mail-ref>', 'list'],
    sequence: [
      'Resolve the current item and existing category names.',
      'Preview add/remove category deltas.',
      'Emit one /add-categories command.',
    ],
    examples: ['/add-categories add="Action Required,Customer"'],
    preview: ['target item', 'categories to add/remove'],
    inverse: 'remove added categories and restore removed categories when captured',
    provenance: 'record item id when available, category names, and changeId',
    failureModes: [
      'category does not exist',
      'read-mode immediate mutation policy',
      'mailbox API unavailable',
    ],
    skillRefs: ['references/outlook-semantics.md'],
  }),
  entry({
    kind: 'compose-appointment',
    surface: 'outlook',
    status: 'catalog-only',
    exposure: 'specialized',
    priority: 'p2',
    command: '/compose-appointment',
    title: 'Outlook appointment compose',
    useWhen: 'open a meeting/appointment draft from grounded details without auto-sending invites',
    hostApis: ['Office.Mailbox.displayNewAppointmentForm'],
    requirementSets: [{ name: 'Mailbox', minVersion: '1.1' }],
    contextKinds: ['calendar-event', 'person', 'mail-item'],
    discovery: ['context analytical inline-preferred', 'properties <source-ref>'],
    sequence: [
      'Ground start/end/location and attendees.',
      'Preview all appointment fields.',
      'Emit one /compose-appointment command; the user sends from Outlook.',
    ],
    examples: [
      '/compose-appointment subject="Project sync" start=2026-07-08T16:00:00Z end=2026-07-08T16:30:00Z',
    ],
    preview: ['subject', 'start/end', 'location', 'attendee hashes'],
    inverse: 'unsent appointment draft remains user-controlled',
    provenance: 'record source metadata, time fields, attendee hashes, and changeId',
    failureModes: [
      'invalid time zone/date',
      'appointment API unavailable',
      'policy disallows attendee edits',
    ],
    skillRefs: ['references/outlook-semantics.md'],
  }),
  entry({
    kind: 'append-page',
    surface: 'onenote',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'page',
    title: 'OneNote synthesized page',
    useWhen: 'create a new grounded page in the active notebook section',
    hostApis: ['OneNote.Section.addPage', 'OneNote.Page.addOutline'],
    requirementSets: [{ name: 'OneNoteApi', minVersion: '1.1' }],
    contextKinds: ['page', 'file', 'brief'],
    discovery: ['outline', 'context inline-preferred', 'properties <section-ref>'],
    sequence: [
      'Read/ground the source material.',
      'Keep citation markers in the synthesized body.',
      'Emit one page command with title and body.',
    ],
    examples: ['page "Meeting notes" "Decisions: ship\\nActions: follow up"'],
    preview: ['target section', 'page title', 'body summary/citation count'],
    inverse:
      'OneNote client API cannot delete the new page; report non-reversible unless Graph path is enabled',
    provenance: 'record page id when returned, title/body hashes, source metadata, and changeId',
    failureModes: ['no active section', 'empty synthesis', 'OneNote web host unavailable'],
    skillRefs: ['references/onenote-semantics.md'],
  }),
  entry({
    kind: 'set-page-title',
    surface: 'onenote',
    status: 'promotable',
    exposure: 'specialized',
    priority: 'p1',
    command: '/set-page-title',
    title: 'OneNote page title',
    useWhen: 'rename the active OneNote page with a reversible title edit',
    hostApis: ['OneNote.Page.title'],
    requirementSets: [{ name: 'OneNoteApi', minVersion: '1.1' }],
    contextKinds: ['page'],
    discovery: ['outline', 'properties <page-ref>', 'open <page-ref>'],
    sequence: [
      'Inspect the page ref.',
      'Preview prior and new title.',
      'Emit one /set-page-title command.',
    ],
    examples: ['/set-page-title title="Design review notes"'],
    preview: ['page id', 'prior title', 'new title'],
    inverse: 'restore prior page title',
    provenance: 'record page id, prior/new title hash, and changeId',
    failureModes: ['page no longer active', 'unsupported OneNote host'],
    skillRefs: ['references/onenote-semantics.md'],
  }),
  entry({
    kind: 'add-outline',
    surface: 'onenote',
    status: 'promotable',
    exposure: 'specialized',
    priority: 'p1',
    command: '/add-outline',
    title: 'OneNote outline insertion',
    useWhen: 'insert a structured HTML/text outline region on the active page',
    hostApis: ['OneNote.Page.addOutline'],
    requirementSets: [{ name: 'OneNoteApi', minVersion: '1.1' }],
    contextKinds: ['page', 'paragraph'],
    discovery: ['outline', 'properties <page-ref>', 'context inline-preferred'],
    sequence: [
      'Resolve the active page.',
      'Preview sanitized HTML/text and approximate placement.',
      'Emit one /add-outline command.',
    ],
    examples: ['/add-outline html="<p>Action items</p>"'],
    preview: ['page id', 'outline content summary', 'placement'],
    inverse: 'delete the created page-content region when host id is captured',
    provenance: 'record page id, outline id, content hash, and changeId',
    failureModes: ['no active page', 'HTML sanitization rejection', 'host id unavailable'],
    skillRefs: ['references/onenote-semantics.md'],
  }),
  entry({
    kind: 'append-rich-text',
    surface: 'onenote',
    status: 'promotable',
    exposure: 'specialized',
    priority: 'p1',
    command: '/append-rich-text',
    title: 'OneNote rich-text paragraph',
    useWhen: 'append a small paragraph to an existing OneNote outline',
    hostApis: ['OneNote.Outline.appendRichText'],
    requirementSets: [{ name: 'OneNoteApi', minVersion: '1.1' }],
    contextKinds: ['page', 'paragraph'],
    discovery: ['list paragraph', 'inspect <paragraph-ref>', 'properties <outline-ref>'],
    sequence: [
      'Resolve the parent outline or paragraph.',
      'Preview the appended paragraph text.',
      'Emit one /append-rich-text command.',
    ],
    examples: ['/append-rich-text outlineId=outline-1 text="Follow up with finance."'],
    preview: ['outline id', 'paragraph text summary'],
    inverse: 'delete the inserted paragraph when host id is captured',
    provenance: 'record outline id, paragraph id, text hash, and changeId',
    failureModes: ['outline unavailable', 'paragraph id unavailable', 'OneNote host unavailable'],
    skillRefs: ['references/onenote-semantics.md'],
  }),
  entry({
    kind: 'add-note-tag',
    surface: 'onenote',
    status: 'promotable',
    exposure: 'specialized',
    priority: 'p1',
    command: '/add-note-tag',
    title: 'OneNote note tag',
    useWhen:
      'mark an existing paragraph as to-do, important, question, or similar native OneNote tag',
    hostApis: ['OneNote.Paragraph.addNoteTag'],
    requirementSets: [{ name: 'OneNoteApi', minVersion: '1.1' }],
    contextKinds: ['paragraph', 'page'],
    discovery: ['list paragraph', 'inspect <paragraph-ref>', 'open <paragraph-ref>'],
    sequence: [
      'Resolve the exact paragraph.',
      'Preview tag type/status.',
      'Emit one /add-note-tag command.',
    ],
    examples: ['/add-note-tag paragraphId=p4 type=toDo status=unknown'],
    preview: ['paragraph id', 'tag type/status'],
    inverse: 'delete the created note tag when host id is captured',
    provenance: 'record paragraph id, tag type/status, and changeId',
    failureModes: ['stale paragraph', 'unsupported tag type', 'host id unavailable'],
    skillRefs: ['references/onenote-semantics.md'],
  }),
  entry({
    kind: 'create-section',
    surface: 'onenote',
    status: 'catalog-only',
    exposure: 'specialized',
    priority: 'p2',
    command: '/create-section',
    title: 'OneNote section creation',
    useWhen: 'create a new notebook section after explicit user confirmation',
    hostApis: ['OneNote.Notebook.addSection'],
    requirementSets: [{ name: 'OneNoteApi', minVersion: '1.1' }],
    contextKinds: ['page'],
    discovery: ['outline', 'properties <notebook-ref>'],
    sequence: [
      'Resolve the target notebook/section group.',
      'Preview the section name and non-reversibility warning.',
      'Emit one /create-section command only for explicit creation requests.',
    ],
    examples: ['/create-section name="Design Reviews"'],
    preview: ['target notebook/group', 'section name', 'non-reversible warning'],
    inverse: 'OneNote client API has no section delete; requires Graph rollback path',
    provenance: 'record notebook/group metadata, section name, and changeId',
    failureModes: ['name collision', 'no delete inverse', 'OneNote web host unavailable'],
    skillRefs: ['references/onenote-semantics.md'],
  }),
  entry({
    kind: 'post-message',
    surface: 'teams',
    status: 'implemented',
    exposure: 'core-verb',
    priority: 'p0',
    command: 'post',
    title: 'Teams staged message',
    useWhen: 'stage a reviewable Teams message from meeting/chat context without silently posting',
    hostApis: ['TeamsJS chat/meeting context', 'TeamsJS sharing/share/openConversation'],
    requirementSets: [{ name: 'TeamsJS', minVersion: '2.x' }],
    contextKinds: ['transcript'],
    discovery: ['read', 'neighbors <segment>', 'properties <thread-ref>'],
    sequence: [
      'Resolve the active chat/meeting context.',
      'Draft short text with source refs when available.',
      'Emit one post command and keep final posting reviewable.',
    ],
    examples: ['post "Action items are ready for review."'],
    preview: ['target context', 'message text summary'],
    inverse: 'staged post is user-reviewable; Graph delete/update requires estate path',
    provenance: 'record context ids, text hash, and changeId',
    failureModes: ['Teams context unavailable', 'compose/stage API unavailable'],
    skillRefs: ['references/teams-semantics.md'],
  }),
  entry({
    kind: 'post-card',
    surface: 'teams',
    status: 'promotable',
    exposure: 'specialized',
    priority: 'p1',
    command: '/post-card',
    title: 'Teams Adaptive Card post',
    useWhen: 'stage a structured Adaptive Card instead of plain chat text',
    hostApis: ['TeamsJS chat/meeting context', 'Microsoft Graph chatMessage with adaptive card'],
    requirementSets: [
      { name: 'TeamsJS', minVersion: '2.x', notes: 'Graph send remains estate-gated' },
    ],
    contextKinds: ['transcript'],
    discovery: ['read', 'neighbors <segment>', 'properties <thread-ref>'],
    sequence: [
      'Resolve the target meeting/chat/thread context.',
      'Preview card JSON, fallback text, and all action URLs.',
      'Emit one /post-card only when Teams/Graph write capability is advertised.',
    ],
    examples: ['/post-card fallbackText="Action items ready"'],
    preview: ['target chat/thread', 'card fallback text', 'screened action URLs'],
    inverse: 'delete/update the posted card only when Graph target id is recorded',
    provenance: 'record card hash, target ids, screened URLs, and changeId',
    failureModes: ['Teams context unavailable', 'Graph estate write not authorized', 'unsafe URL'],
    skillRefs: ['references/teams-semantics.md'],
  }),
  entry({
    kind: 'post-channel-message',
    surface: 'teams',
    status: 'estate-gated',
    exposure: 'estate',
    priority: 'p2',
    command: '/post-channel-message',
    title: 'Teams channel message via Graph',
    useWhen: 'post to a channel only when tenant estate-write policy and Graph scopes are enabled',
    hostApis: ['Microsoft Graph POST /teams/{team-id}/channels/{channel-id}/messages'],
    requirementSets: [{ name: 'Graph', minVersion: 'ChannelMessage.Send' }],
    contextKinds: ['transcript'],
    discovery: ['properties <team-ref>', 'properties <channel-ref>', 'context reference-preferred'],
    sequence: [
      'Resolve team/channel ids from trusted context.',
      'Preview message text/card and all links.',
      'Emit only when estate Graph write capability is advertised.',
    ],
    examples: [
      '/post-channel-message teamId=<team> channelId=<channel> text="Standup notes ready"',
    ],
    preview: ['team/channel ids', 'message summary', 'link screening'],
    inverse: 'delete/update the message only when Graph returns message id and policy allows',
    provenance: 'record team/channel/message ids, text hash, link-screening result, and changeId',
    failureModes: ['missing Graph scope', 'tenant policy denial', 'unsafe URL', 'Graph throttling'],
    skillRefs: ['references/teams-semantics.md'],
  }),
  entry({
    kind: 'update-message',
    surface: 'teams',
    status: 'estate-gated',
    exposure: 'estate',
    priority: 'p2',
    command: '/update-message',
    title: 'Teams message/card update via Graph',
    useWhen: 'update a previously posted Teams message/card with a recorded message id',
    hostApis: [
      'Microsoft Graph PATCH /teams/{team-id}/channels/{channel-id}/messages/{message-id}',
    ],
    requirementSets: [{ name: 'Graph', minVersion: 'ChannelMessage.Send' }],
    contextKinds: ['transcript'],
    discovery: ['properties <message-ref>', 'open <message-ref>'],
    sequence: [
      'Resolve the exact posted message id.',
      'Preview prior and new message/card content.',
      'Emit only when estate Graph write capability is advertised.',
    ],
    examples: [
      '/update-message teamId=<team> channelId=<channel> messageId=<message> text="Updated notes"',
    ],
    preview: ['message id', 'before/after summary', 'card/link screening'],
    inverse: 'restore prior message content when Graph supports the target',
    provenance: 'record message id, prior/new content hashes, and changeId',
    failureModes: ['message not editable', 'missing Graph scope', 'unsafe card action URL'],
    skillRefs: ['references/teams-semantics.md'],
  }),
  entry({
    kind: 'create-online-meeting',
    surface: 'teams',
    status: 'estate-gated',
    exposure: 'estate',
    priority: 'p3',
    command: '/create-online-meeting',
    title: 'Teams online meeting via Graph',
    useWhen: 'create an online meeting only through an estate-approved Graph write path',
    hostApis: ['Microsoft Graph POST /me/onlineMeetings'],
    requirementSets: [{ name: 'Graph', minVersion: 'OnlineMeetings.ReadWrite' }],
    contextKinds: ['calendar-event', 'person'],
    discovery: ['context analytical reference-preferred', 'properties <calendar-ref>'],
    sequence: [
      'Resolve meeting time and participants from trusted context.',
      'Preview subject, time, participants, and tenant policy.',
      'Emit only when estate meeting capability is advertised.',
    ],
    examples: [
      '/create-online-meeting subject="Design review" startDateTime=2026-07-08T16:00:00Z endDateTime=2026-07-08T16:30:00Z',
    ],
    preview: ['subject', 'time window', 'participant hashes', 'policy result'],
    inverse: 'delete the created online meeting when Graph returns id and policy allows',
    provenance: 'record meeting id, time fields, participant hashes, and changeId',
    failureModes: ['missing Graph scope', 'tenant policy denial', 'invalid time zone/date'],
    skillRefs: ['references/teams-semantics.md'],
  }),
];

export function capabilityRegistryEntries(): CapabilityRegistryEntry[] {
  return [...CAPABILITY_REGISTRY];
}

export function registryEntryForKind(kind: ActuationKind): CapabilityRegistryEntry | undefined {
  return CAPABILITY_REGISTRY.find((entry) => entry.kind === kind);
}

export function registryEntryForKindAndSurface(
  kind: ActuationKind,
  surface: Surface,
): CapabilityRegistryEntry | undefined {
  return CAPABILITY_REGISTRY.find((entry) => entry.kind === kind && entry.surface === surface);
}

export function registryEntriesForSurface(surface: Surface): CapabilityRegistryEntry[] {
  return CAPABILITY_REGISTRY.filter((entry) => entry.surface === surface);
}

export function implementedRegistryEntriesForSurface(surface: Surface): CapabilityRegistryEntry[] {
  return registryEntriesForSurface(surface).filter((entry) => entry.status === 'implemented');
}

export function implementedRegistryKindsForSurface(surface: Surface): ActuationKind[] {
  return implementedRegistryEntriesForSurface(surface).map((entry) => entry.kind);
}

export function assertCapabilityRegistryConsistent(
  entries: readonly CapabilityRegistryEntry[] = CAPABILITY_REGISTRY,
): CapabilityRegistryEntry[] {
  const parsed = entries.map((entry) => CapabilityRegistryEntrySchema.parse(entry));
  const seen = new Set<string>();
  const errors: string[] = [];
  for (const entry of parsed) {
    const key = `${entry.surface}:${entry.kind}`;
    if (seen.has(key)) errors.push(`duplicate capability registry entry "${key}"`);
    seen.add(key);
    if (entry.exposure === 'core-verb' && entry.command.startsWith('/')) {
      errors.push(`${key} is core-verb but uses slash command ${entry.command}`);
    }
    if (entry.exposure === 'specialized' && !entry.command.startsWith('/')) {
      errors.push(`${key} is specialized but command is not slash-prefixed`);
    }
    if (entry.status === 'implemented' && entry.priority !== 'p0') {
      errors.push(`${key} is implemented but not p0`);
    }
  }
  if (errors.length > 0) {
    throw new Error(`capability registry is inconsistent:\n  - ${errors.join('\n  - ')}`);
  }
  return parsed;
}

function entry(input: CapabilityRegistryEntry): CapabilityRegistryEntry {
  return CapabilityRegistryEntrySchema.parse(input);
}
